spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:mysql://localhost:23306/portfolio_board?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: root123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: portfolio.board-application-2024.secret_key
  token.expired-time-ms: 2592000000 # 30 days